import express from "express";
import productsRoutes from "./routes/productsRoutes.js";
import cartsRoutes from "./routes/cartsRoutes.js";
import mainRoutes from "./routes/mainRoutes.js";
const app = express();
const PORT = 8080;
app.listen(PORT, console.log("Servidor corriendo en:http://localhost:" + PORT));
app.use("/api/products/", productsRoutes);
app.use("/api/carts", cartsRoutes);
app.use("/", mainRoutes);
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
